#!/bin/bash

# showDocu
# This file is part of arduino-nano-rgb
#
# Copyright (C) 2014 - Mirco Bertelli
#
# arduino-nano-rgb is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# arduino-nano-rgb is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with arduino-nano-rgb. If not, see <http://www.gnu.org/licenses/>.

DOC_DIR="doc"
DOC_INDEX="index.html"

GRAPH_FILE_SRC="rgb.dot"
GRAPH_FILE="graph.png"
LAYOUT_FILE="arduino_rgb.png"

CWD="$( pwd )"

doxygen -h >& /dev/null
if [ $? != 0 ]; then
	echo -e "doxygen non trovato.\nImpossibile generare lo documentazione."
	exit 1
fi

dot -? >& /dev/null
if [ $? != 0 ]; then
	echo -e "dot non trovato.\nImpossibile generare lo documentazione."
	exit 1
fi

mkdir $DOC_DIR
doxygen
dot -Tpng $GRAPH_FILE_SRC > $DOC_DIR/$GRAPH_FILE

xdg-open "file://$CWD/$DOC_DIR/html/$DOC_INDEX" &
xdg-open "file://$CWD/$DOC_DIR/$GRAPH_FILE" &
xdg-open "file://$CWD/$DOC_DIR/$LAYOUT_FILE" &

exit 0